services:
  - type: web
    name: promts
    runtime: node
    buildCommand: rm -rf node_modules && npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "20.11.0"
      - key: GEMINI_API_KEY
        sync: false
